
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: auth-deployment
  ports:
    - port: 82
      targetPort: 5001 
      nodePort: 30923  
