apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-service
  labels:
    app: url
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url
  template:
    metadata:
      labels:
        app: url
    spec:
      containers:
      - name: url
        image: junidock/urls_service
        ports:
        - containerPort: 5000
