apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-deployment
  template:
    metadata:
      labels:
        app: url-deployment
    spec:
      containers:
      - name: url-deployment
        image: urls_service
        ports:
        - containerPort: 5000
